name: Daily Seatalk Message

on:
  schedule:
    # 这里的 09:45 UTC 等于北京时间 17:45
    - cron: '45 9 * * *'
  workflow_dispatch: # 允许你手动点击运行测试

jobs:
  send_msg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python main.py
